<?php

namespace Database\Factories;

use App\Models\ConsentRecord;
use App\Models\Patient;
use App\Models\Practice;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<ConsentRecord>
 */
class ConsentRecordFactory extends Factory
{
    protected $model = ConsentRecord::class;

    public function definition(): array
    {
        return [
            'practice_id'      => Practice::factory(),
            'patient_id'       => Patient::factory(),
            'appointment_id'   => null,
            'status'           => 'missing',
            'signed_on'        => null,
            'consent_given_by' => null,
            'consent_summary'  => null,
            'notes'            => null,
            // access_token auto-generated by HasAccessToken::bootHasAccessToken
        ];
    }

    /** Consent has been signed. */
    public function complete(): static
    {
        return $this->state(fn (array $attributes) => [
            'status'           => 'complete',
            'signed_on'        => fake()->dateTimeBetween('-30 days', '-1 day'),
            'consent_given_by' => fake()->name(),
            'consent_summary'  => fake()->optional(0.6)->randomElement([
                'I understand the treatment plan and agree to proceed.',
                'Consent given on behalf of myself. No known allergies to treatment.',
                'I have reviewed the informed consent document and agree to the terms.',
                'Agreeing to treatment. Please note I have a latex sensitivity.',
                'Consent given. I may need shorter sessions due to a low pain threshold.',
            ]),
            'notes' => fake()->optional(0.3)->randomElement([
                'Please keep sessions to 45 minutes.',
                'Call before texting.',
                'Prefer female practitioners if available.',
                'Billing to be sent to partner\'s email.',
            ]),
        ]);
    }

    /** Consent is still pending (default alias for readability). */
    public function missing(): static
    {
        return $this->state(['status' => 'missing']);
    }
}
