<?php

namespace Database\Factories;

use App\Models\IntakeSubmission;
use App\Models\Patient;
use App\Models\Practice;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<IntakeSubmission>
 */
class IntakeSubmissionFactory extends Factory
{
    protected $model = IntakeSubmission::class;

    public function definition(): array
    {
        return [
            'practice_id'      => Practice::factory(),
            'patient_id'       => Patient::factory(),
            'appointment_id'   => null,
            'status'           => 'missing',
            'submitted_on'     => null,
            'reason_for_visit' => null,
            'current_concerns' => null,
            'relevant_history' => null,
            'medications'      => null,
            'notes'            => null,
            'summary_text'     => null,
            // access_token auto-generated by HasAccessToken::bootHasAccessToken
        ];
    }

    /** Intake has been submitted with content. */
    public function complete(): static
    {
        return $this->state(fn () => [
            'status'           => 'complete',
            'submitted_on'     => \fake()->dateTimeBetween('-30 days', '-1 day'),
            'reason_for_visit' => \fake()->randomElement([
                'Persistent lower back pain radiating to left leg.',
                'Chronic migraines, 3–4 times per week for the past month.',
                'Shoulder tension and reduced range of motion.',
                'Fatigue and difficulty sleeping for the past three weeks.',
                'Digestive issues, bloating after meals.',
                'Anxiety and stress management.',
                'Neck stiffness after long hours at computer.',
            ]),
            'current_concerns' => \fake()->randomElement([
                'Pain is worse in the morning and improves through the day.',
                'Headaches begin behind the eyes and spread to the temples.',
                'Shoulder pain worsens when reaching overhead.',
                'Difficulty falling asleep, waking at 3–4 am.',
                'Bloating most noticeable after dinner.',
                'Tension in chest and shallow breathing.',
            ]),
            'relevant_history' => \fake()->randomElement([
                'No prior surgeries. Family history of hypertension.',
                'Herniated disc (L4-L5) diagnosed 2019, managed conservatively.',
                'Rotator cuff strain 2022, resolved with PT.',
                'No significant medical history.',
                'IBS diagnosis 2018. Managed with diet.',
                'Anxiety disorder, currently on no medication.',
            ]),
            'medications' => \fake()->randomElement([
                'Ibuprofen 400mg as needed.',
                'None.',
                'Magnesium glycinate 400mg nightly.',
                'Vitamin D3 2000IU daily. Fish oil 1000mg.',
                'Metformin 500mg twice daily.',
                'Sertraline 50mg daily.',
            ]),
            'notes' => \fake()->optional(0.5)->randomElement([
                'Prefer afternoon appointments.',
                'Please use thinner needles if possible.',
                'First time trying acupuncture — a little nervous.',
                'Had a bad reaction to deep tissue massage in the past.',
                'Would like to discuss herbal supplements.',
            ]),
        ]);
    }

    /** Intake is still pending (default alias for readability). */
    public function missing(): static
    {
        return $this->state(['status' => 'missing']);
    }
}
