export const SCENES = [
	{
		slug: 'problem',
		label: 'Problem',
		title: 'Small practices juggle too many disconnected tools.',
		body: 'Notes, forms, scheduling, follow-up, reporting, and setup often live in separate systems. That slows staff down and makes the day harder to manage.',
		callout: 'The problem is not a lack of software. It is fragmented workflow.',
		asset: '01-problem.svg',
		bullets: ['Notes in one place', 'Forms somewhere else', 'Follow-up and reporting disconnected'],
		durationInFrames: 240,
	},
	{
		slug: 'positioning',
		label: 'Positioning',
		title: 'Practiq is documentation-first software for practices that put care before billing.',
		body: 'Built for acupuncture, massage, chiropractic, physiotherapy, and wellness clinics that want calmer daily workflow without enterprise overhead.',
		callout: 'Professional-to-professional software for small teams and solo practices.',
		asset: '02-positioning.svg',
		bullets: ['Documentation-first workflow', 'Care before billing', 'Built for small practices'],
		durationInFrames: 240,
	},
	{
		slug: 'setup-checklist',
		label: 'Setup Readiness',
		title: 'The setup checklist shows what to configure first.',
		body: 'Practiq helps practices verify the basics before they start sending patient links or relying on scheduling workflows.',
		callout: 'Practitioners, treatment types, working hours, website links, and acknowledgements are visible in one place.',
		asset: '03-setup-checklist.svg',
		bullets: ['Practice profile and slug', 'Practitioners and treatment types', 'Working hours and readiness items'],
		durationInFrames: 240,
	},
	{
		slug: 'website-links',
		label: 'Website Links',
		title: 'Public website links give patients clear entry points.',
		body: 'Practices can place stable links on their site for new patient requests, existing patient access, and appointment requests.',
		callout: 'No guessing which form or portal link to send.',
		asset: '04-website-links.svg',
		bullets: ['New patient request', 'Existing patient access', 'Appointment request with secure routing'],
		durationInFrames: 240,
	},
	{
		slug: 'appointment-request',
		label: 'Appointment Requests',
		title: 'Patients request appointments. Staff confirms the final time.',
		body: 'Patients can submit treatment preferences, practitioner preferences, and scheduling notes without implying direct self-booking.',
		callout: 'Appointment requests with staff confirmation, not automatic booking.',
		asset: '05-appointment-request.svg',
		bullets: ['Treatment and practitioner preferences', 'Structured request details', 'No automatic appointment creation'],
		durationInFrames: 240,
	},
	{
		slug: 'calendar-context',
		label: 'Staff Scheduling',
		title: 'Staff schedules from the request into practitioner calendar context.',
		body: 'Practiq surfaces working hours, blocked time, existing appointments, and deterministic suggestions while keeping staff in control.',
		callout: 'Calendar context supports the decision. It does not replace it.',
		asset: '06-calendar-context.svg',
		bullets: ['Working hours and blocks', 'Existing appointments', 'Deterministic staff-side scheduling'],
		durationInFrames: 240,
	},
	{
		slug: 'visit-notes',
		label: 'Visit Notes',
		title: 'Choose simple note mode or SOAP / insurance mode.',
		body: 'Practitioners can document the way the visit actually happened, whether that means natural visit notes or more structured documentation.',
		callout: 'Documentation-first means charting supports care, not the other way around.',
		asset: '07-visit-notes.svg',
		bullets: ['Simple visit notes', 'SOAP / insurance workflows', 'Visit-centered documentation'],
		durationInFrames: 240,
	},
	{
		slug: 'ai-assistance',
		label: 'Optional AI',
		title: 'AI assistance stays optional, reviewed, and practitioner-controlled.',
		body: 'Practiq can help with drafts, summaries, translations, and documentation checks, but the practitioner remains responsible for review and final use.',
		callout: 'AI acknowledgement is tracked before first AI use.',
		asset: '08-ai-assistance.svg',
		bullets: ['Draft support only', 'Practitioner review required', 'No automatic clinical decisions'],
		durationInFrames: 240,
	},
	{
		slug: 'forms-review',
		label: 'Forms Review',
		title: 'Online forms are submitted by patients and reviewed by staff.',
		body: 'Forms, intake, and consent records stay connected to the patient workflow without silently overwriting charts.',
		callout: 'Patients submit. Staff reviews. Records stay intentional.',
		asset: '09-forms-review.svg',
		bullets: ['Sent, submitted, reviewed', 'No silent demographic overwrite', 'Patient portal foundation'],
		durationInFrames: 240,
	},
	{
		slug: 'follow-up',
		label: 'Follow-Up',
		title: 'The Follow-Up Center keeps invite-back work from getting lost.',
		body: 'Staff can identify patients who may need attention, prepare drafts, review translations, and keep communication history visible.',
		callout: 'Follow-up becomes a managed workflow instead of a memory task.',
		asset: '10-follow-up.svg',
		bullets: ['Patient attention list', 'Invite-back drafts', 'Communication history'],
		durationInFrames: 240,
	},
	{
		slug: 'reports-exports',
		label: 'Reports & Exports',
		title: 'Practice statistics and financial exports help with bookkeeping.',
		body: 'Collected revenue summaries, payment method totals, practitioner breakdowns, and line-item CSV exports are available without claiming full accounting software.',
		callout: 'Useful financial reporting for small practices, not a full accounting suite.',
		asset: '11-reports-exports.svg',
		bullets: ['financial_summary.csv', 'checkout_payments.csv', 'checkout_line_items.csv'],
		durationInFrames: 240,
	},
	{
		slug: 'cta',
		label: 'CTA',
		title: 'Help shape Practiq, or start a free trial when the workflow fits.',
		body: 'The Founding Practitioner Review Program and in-app questionnaire keep practitioner feedback close to the product while practices evaluate the platform.',
		callout: 'Professional, practical software for small practices.',
		asset: '12-cta.svg',
		bullets: ['Founding Practitioner Review Program', 'Free trial', 'Replace placeholders with real screenshots later'],
		durationInFrames: 240,
	},
];

export const TOTAL_FRAMES = SCENES.reduce((sum, scene) => sum + scene.durationInFrames, 0);
